apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insighthub-payloads
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.payloads.storage }}
